name: on-push

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: "install and build"
        run: |
          npm install
          npm run build
      - name: "check ts types"
        run: |
          npm run check
      - name: "test"
        run: |
          npm run test
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: "install and build"
        run: |
          cd docs
          npm install
          npm run build
      - name: "deploy"
        if: ${{ github.ref == 'refs/heads/main' || github.refs == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build
